version: '2.3'

services:
  microros:
    image: husarion/micro-ros-agent:humble-3.1.2-20230204-stable
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888